spring:
  application:
    name: provider
  main:
    allow-bean-definition-overriding: true

dubbo:
  scan:
    base-packages: com.grq.provider.service
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
  registry:
    address: nacos://localhost:8848
