spring:
  application:
    name: business-oauth2
  main:
    allow-bean-definition-overriding: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

#开启 Feign xhttp 的方式
feign:
  okhttp:
    enabled: true
  httpclient:
    enabled: false


dubbo:
  scan:
    base-packages: com.grq.business.controller,com.grq.business.service
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
  registry:
    address: nacos://localhost:8848
server:
  port: 9001

management:
  endpoints:
    web:
      exposure:
        include: "*"
business:
  oauth2:
    grant_type: password
    client_id: client
    client_secret: secret